feat(drivers): Added USB JTAG debug unit driver
espressif/esp-win-usb-drivers pull request #4
Opened 2024-07-10 07:34 UTC by jakub-kocka

Espressif has an [ESP32 USB JTAG driver](https://github.com/espressif/idf-installer/tree/main?tab=readme-ov-file#manual-installation-of-drivers) which is installed by the IDF installer.

This PR is adding the source files to this repo which includes all the other drivers to gather everything in one place.

- internal tracker IDF-3583

2024-07-12 05:52 UTC, jakub-kocka commented
The driver has been released as a draft (https://github.com/espressif/esp-win-usb-drivers/releases) and seems to work as expected.

Can you please take a look @dobairoland?

2024-07-12 06:22 UTC, jakub-kocka commented
I have updated the `README.md` to clarify how to install the driver.

[preview](https://github.com/espressif/esp-win-usb-drivers/blob/feat/esp32_jtag_driver/README.md)

2024-07-12 07:06 UTC, dobairoland requested changes
We need to solve the licensing issue as we discussed in person. LGTM otherwise. Thank you!

2024-07-15 08:59 UTC, jakub-kocka commented
> We need to solve the licensing issue as we discussed in person. LGTM otherwise. Thank you!

I have provided some changes, what do you think about this approach @dobairoland?

2024-07-15 10:10 UTC, dobairoland commented on README.md
>  This document and the attached source code are released as Free Software under Apache License Version 2 or later. See the accompanying [LICENSE](LICENSE) file for a copy.
Does it makes sense to keep this? Is something under Apache 2.0 (including the sources to build the driver)?

I'm thinking that there it could just be stated that licensing is defined in each driver separately.

2024-07-15 10:11 UTC, dobairoland commented on drivers/esp32-usb-jtag/README.md
> +* libusb  - [author's source](https://github.com/libusb/libusb) | [LGPL-2.1 license](https://github.com/libusb/libusb/blob/master/COPYING)
Can we state the exact version of the sources used to generate the binaries?

2024-07-15 10:27 UTC, jakub-kocka commented on README.md
>  This document and the attached source code are released as Free Software under Apache License Version 2 or later. See the accompanying [LICENSE](LICENSE) file for a copy.
We can provide the `./ci/` PowerShell scripts and all the `.inf` files under Apache 2.0 (even if it wraps the original WinUSB, but in most of the drivers the `.dll` files are not a part of the driver). The `.inf` file and `.cat` are signed by Espressif so the copyright is obvious, when the files are modified it will stop working anyway.

I think it would be nice to have one global license and an option to change it for a specific driver if needed.

2024-07-15 10:31 UTC, jakub-kocka commented on drivers/esp32-usb-jtag/README.md
> +* libusb  - [author's source](https://github.com/libusb/libusb) | [LGPL-2.1 license](https://github.com/libusb/libusb/blob/master/COPYING)
I am not sure if this will be possible. I can ask about it.

Also, I can try to backtrace (or approximate) it according to the date of creation of the files. Would it be OK to have at least something rather than nothing?

2024-07-15 11:05 UTC, dobairoland commented on drivers/esp32-usb-jtag/README.md
> +* libusb  - [author's source](https://github.com/libusb/libusb) | [LGPL-2.1 license](https://github.com/libusb/libusb/blob/master/COPYING)
Licensing is tricky. If you distribute the binary then the sources should be as well (like binaries & sources archive). If we don't provide the sources with the binary distribution then I think stating the version of the sources is a must.

2024-07-15 11:08 UTC, dobairoland commented on README.md
>  This document and the attached source code are released as Free Software under Apache License Version 2 or later. See the accompanying [LICENSE](LICENSE) file for a copy.
> I think it would be nice to have one global license and an option to change it for a specific driver if needed.

Licenses don't work that way. If the project is distributed under a license then its parts cannot "overwrite" the default license because some rules are implied by it. For your case, you cannot add libusb with LGPL license. You could do this with BSD, MIT or similar, less restrictive licenses.

2024-07-16 10:50 UTC, jakub-kocka commented
I have changed the approach based on our in-person discussion @dobairoland.

- global `LICENSE` file was removed
- every driver has its own `README` and `LICENSE` file
- global `README` was updated to reflect this

Here is the preview branch: https://github.com/espressif/esp-win-usb-drivers/tree/feat/esp32_jtag_driver?tab=readme-ov-file

2024-07-16 13:22 UTC, dobairoland commented on drivers/esp-wrover-kit/README.md
> +This source code is released as Free Software under Apache License Version 2 or later. See the accompanying [LICENSE](LICENSE) file for a copy.
The license file contain the Apache 2.0 license.

2024-07-16 13:47 UTC, dobairoland commented on drivers/esp-wrover-kit/README.md
> +This source code is released as Free Software under Apache License Version 2 or later. See the accompanying [LICENSE](LICENSE) file for a copy.
Sorry, I've got confused with "2 or later". For Apache, we don't use the "or later" part.

This is a leftover from GPL2+, which is "version 2 or later". There is also GPL2 which is without "or later". Apache 2.0 is also without "or later".

2024-07-17 06:22 UTC, jakub-kocka commented on drivers/esp-wrover-kit/README.md
> +This source code is released as Free Software under Apache License Version 2 or later. See the accompanying [LICENSE](LICENSE) file for a copy.
Thank you for pointing this out. I have changed this.

2024-07-17 07:42 UTC, dobairoland approved these changes
LGTM

2024-07-17 10:45 UTC, jakub-kocka commented
Thanks for the review! I am merging this and will add the jtag driver into releases.

2024-07-17 10:45 UTC, merged